Fixes #56
data-mie/dbt-profiler pull request #57
Opened 2022-11-03 19:28 UTC by dweaver33

## Description & motivation
This will allow a user to specify a `WHERE` clause so the user can filter out which data to profile.  

## Checklist
- [ ] I have verified that these changes work locally on the following warehouses (Note: it's okay if you do not have access to all warehouses, this helps us understand what has been covered):
    - [ ] Postgres
    - [ ] BigQuery
    - [ ] Snowflake
    - [ ] Redshift
    - [ ] SQL Server
- [ ] I have written tests for new macros (either as dbt schema tests in `integration_tests/models`, dbt data tests in `integration_tests/tests` or integration tests in the [CI workflow](workflows/main.yml))
- [ ] I have updated the README.md (if applicable)

2022-11-03 19:29 UTC, dweaver33 commented
@stumelius, first attempt.  Let me know if there's any changes needed.

2022-11-11 13:26 UTC, stumelius commented
@dweaver33 Great work, the code looks good! I left a few comments for you.

2022-11-14 15:43 UTC, dweaver33 commented
@stumelius, I think you need to mark your review as finished so I can see the comments.

2022-11-14 16:23 UTC, stumelius requested changes

2022-11-14 16:25 UTC, stumelius commented
@dweaver33 Lol, my bad 🤦 There you go!

2022-11-15 15:47 UTC, merged